<?php
declare(strict_types=1); session_start(); require 'config.php'; require 'auth.php'; require_once 'wardrobe_common.php';
$id=(int)($_GET['id']??0); if($id<1){header('Location: wardrobe.php');exit;}
function load_item(mysqli $link,int $id):?array{$s=$link->prepare('SELECT * FROM WardrobeItems WHERE WardrobeItemID=?');$s->bind_param('i',$id);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return $r?:null;}
$item=load_item($link,$id); if(!$item){http_response_code(404);exit('Wardrobe item not found');} $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'save'; $uid=(int)$_SESSION['userID'];
 if($action==='delete'){ $s=$link->prepare('UPDATE WardrobeItems SET DeletedAt=NOW(),UpdatedByUserID=? WHERE WardrobeItemID=?');$s->bind_param('ii',$uid,$id);$s->execute();$_SESSION['wardrobe_notice']='Item moved to the bin.';header('Location: wardrobe.php');exit;}
 if($action==='restore'){ $s=$link->prepare('UPDATE WardrobeItems SET DeletedAt=NULL,UpdatedByUserID=? WHERE WardrobeItemID=?');$s->bind_param('ii',$uid,$id);$s->execute();$_SESSION['wardrobe_notice']='Item restored.';header('Location: wardrobe_item.php?id='.$id);exit;}
 try{
  $name=trim($_POST['name']??'');$category=$_POST['category']??'';if($name===''||!in_array($category,wardrobe_allowed_categories(),true))throw new RuntimeException('Name and category are required.');
  $sub=trim($_POST['subcategory']??'')?:null;$brand=trim($_POST['brand']??'')?:null;$colour=trim($_POST['primary_colour']??'')?:null;
  $secondary=json_encode(wardrobe_csv_array($_POST['secondary_colours']??''));$pattern=trim($_POST['pattern']??'')?:null;$material=trim($_POST['material']??'')?:null;
  $thickness=$_POST['thickness']?:null;$fit=trim($_POST['fit']??'')?:null;$formality=$_POST['formality']?:null;$seasons=json_encode($_POST['seasons']??[]);
  $occasions=json_encode(wardrobe_csv_array($_POST['occasions']??''));$tags=json_encode(wardrobe_csv_array($_POST['tags']??''));$notes=trim($_POST['notes']??'')?:null;$fav=isset($_POST['favourite'])?1:0;
  $catalogue=$_POST['catalogue_image_preference']??'processed';$detail=$_POST['detail_image_preference']??'processed';
  if(!in_array($catalogue,wardrobe_allowed_image_preferences(),true)||!in_array($detail,wardrobe_allowed_image_preferences(),true))throw new RuntimeException('Invalid image preference.');
  $s=$link->prepare("UPDATE WardrobeItems SET Name=?,Category=?,Subcategory=?,Brand=?,PrimaryColour=?,SecondaryColours=?,Pattern=?,Material=?,Thickness=?,Fit=?,Formality=?,Seasons=?,Occasions=?,Tags=?,Notes=?,Favourite=?,CatalogueImagePreference=?,DetailImagePreference=?,MetadataSource='user_confirmed',ProcessingStatus='ready',UpdatedByUserID=? WHERE WardrobeItemID=?");
  $s->bind_param('sssssssssssssssissii',$name,$category,$sub,$brand,$colour,$secondary,$pattern,$material,$thickness,$fit,$formality,$seasons,$occasions,$tags,$notes,$fav,$catalogue,$detail,$uid,$id);$s->execute();$s->close();
  $_SESSION['wardrobe_notice']='Changes saved.';header('Location: wardrobe_item.php?id='.$id);exit;
 }catch(Throwable $e){$error=$e->getMessage();}
}
$item=load_item($link,$id);$seasons=wardrobe_json_array($item['Seasons']);$secondary=implode(', ',wardrobe_json_array($item['SecondaryColours']));$occasions=implode(', ',wardrobe_json_array($item['Occasions']));$tags=implode(', ',wardrobe_json_array($item['Tags']));
$page_title='Edit '.$item['Name'];$wardrobe_modern=true;include 'header.php';
?>
<div class="container py-4"><div class="d-flex justify-content-between mb-3"><a class="btn btn-outline-secondary btn-sm" href="wardrobe_item.php?id=<?=$id?>">← Cancel</a><h1 class="h4 mb-0">Edit clothing</h1></div><?php if($error):?><div class="alert alert-danger"><?=wardrobe_h($error)?></div><?php endif;?>
<form method="post" class="card shadow-sm"><div class="card-body row g-3">
<div class="col-md-8"><label class="form-label">Name</label><input required class="form-control" name="name" value="<?=wardrobe_h($item['Name'])?>"></div>
<div class="col-md-4"><label class="form-label">Category</label><select required class="form-select" name="category"><?php foreach(wardrobe_allowed_categories() as $c):?><option value="<?=$c?>" <?=$item['Category']===$c?'selected':''?>><?=ucwords($c)?></option><?php endforeach;?></select></div>
<?php $simple=['subcategory'=>'Subcategory','brand'=>'Brand','primary_colour'=>'Primary colour','pattern'=>'Pattern','material'=>'Material','fit'=>'Fit'];$cols=['subcategory'=>'Subcategory','brand'=>'Brand','primary_colour'=>'PrimaryColour','pattern'=>'Pattern','material'=>'Material','fit'=>'Fit'];foreach($simple as $n=>$label):?><div class="col-md-6"><label class="form-label"><?=$label?></label><input class="form-control" name="<?=$n?>" value="<?=wardrobe_h($item[$cols[$n]]??'')?>"></div><?php endforeach;?>
<div class="col-md-6"><label class="form-label">Secondary colours</label><input class="form-control" name="secondary_colours" value="<?=wardrobe_h($secondary)?>"></div>
<div class="col-md-3"><label class="form-label">Thickness</label><select class="form-select" name="thickness"><option value="">Unknown</option><?php foreach(['very_light','light','medium','heavy','very_heavy'] as $v):?><option value="<?=$v?>" <?=$item['Thickness']===$v?'selected':''?>><?=ucwords(str_replace('_',' ',$v))?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label">Formality</label><select class="form-select" name="formality"><option value="">Unknown</option><?php foreach(['very_casual','casual','smart_casual','formal','very_formal'] as $v):?><option value="<?=$v?>" <?=$item['Formality']===$v?'selected':''?>><?=ucwords(str_replace('_',' ',$v))?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label">Seasons</label><div><?php foreach(['spring','summer','autumn','winter'] as $v):?><label class="me-3"><input type="checkbox" name="seasons[]" value="<?=$v?>" <?=in_array($v,$seasons,true)?'checked':''?>> <?=ucfirst($v)?></label><?php endforeach;?></div></div>
<div class="col-md-6"><label class="form-label">Occasions</label><input class="form-control" name="occasions" value="<?=wardrobe_h($occasions)?>"></div><div class="col-md-6"><label class="form-label">Tags</label><input class="form-control" name="tags" value="<?=wardrobe_h($tags)?>"></div>
<div class="col-md-6"><label class="form-label">Catalogue card image</label><select class="form-select" name="catalogue_image_preference"><?php foreach(wardrobe_allowed_image_preferences() as $v):?><option value="<?=$v?>" <?=($item['CatalogueImagePreference']??'processed')===$v?'selected':''?>><?=ucfirst($v==='processed'?'clean':$v)?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label">Detail page image</label><select class="form-select" name="detail_image_preference"><?php foreach(wardrobe_allowed_image_preferences() as $v):?><option value="<?=$v?>" <?=($item['DetailImagePreference']??'processed')===$v?'selected':''?>><?=ucfirst($v==='processed'?'clean':$v)?></option><?php endforeach;?></select></div>
<div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" rows="4" name="notes"><?=wardrobe_h($item['Notes'])?></textarea></div><div class="col-12"><label><input type="checkbox" name="favourite" <?=$item['Favourite']?'checked':''?>> Favourite</label></div>
</div>
<div class="card shadow-sm mt-4"><div class="card-body"><h2 class="h5">Image tools</h2><p class="text-muted small">Generated images are saved as separate derivatives; original uploads are never replaced.</p><div class="d-grid gap-2 d-md-flex"><a class="btn btn-outline-secondary" href="wardrobe_process_images.php?id=<?=$id?>">Generate clean catalogue images</a><a class="btn btn-outline-dark" href="wardrobe_generate_model_images.php?id=<?=$id?>">Generate faceless male-model images</a><a class="btn btn-outline-primary" href="wardrobe_analyse.php?id=<?=$id?>">Analyse or re-analyse garment</a></div></div></div>
<div class="card-footer d-flex justify-content-between"><div><?php if($item['DeletedAt']):?><button class="btn btn-outline-success" name="action" value="restore">Restore</button><?php else:?><button class="btn btn-outline-danger" name="action" value="delete" onclick="return confirm('Move this item to the bin?')">Delete</button><?php endif;?></div><button class="btn btn-primary" name="action" value="save">Save changes</button></div></form></div><?php include 'footer.php';?>
