<?php
declare(strict_types=1); session_start(); require 'config.php'; require 'auth.php'; require_once 'wardrobe_common.php';
$q=trim($_GET['q']??''); $category=trim($_GET['category']??''); $deleted=($_GET['deleted']??'')==='1';
$where=$deleted?'DeletedAt IS NOT NULL':'DeletedAt IS NULL'; $types=''; $params=[];
if($q!==''){ $where.=' AND (Name LIKE ? OR Brand LIKE ? OR PrimaryColour LIKE ? OR Tags LIKE ? OR Subcategory LIKE ? OR Material LIKE ?)'; $n="%$q%"; $types.='ssssss'; $params=[$n,$n,$n,$n,$n,$n]; }
if($category!==''){ $where.=' AND Category=?'; $types.='s'; $params[]=$category; }
$stmt=$link->prepare("SELECT * FROM WardrobeItems WHERE $where ORDER BY Favourite DESC, CreatedAt DESC, UpdatedAt DESC"); if($types)$stmt->bind_param($types,...$params); $stmt->execute(); $res=$stmt->get_result(); $items=[]; while($r=$res->fetch_assoc())$items[]=$r; $stmt->close();
$counts=[];$countRes=$link->query("SELECT Category,COUNT(*) Total FROM WardrobeItems WHERE DeletedAt IS NULL GROUP BY Category");if($countRes)while($r=$countRes->fetch_assoc())$counts[$r['Category']]=(int)$r['Total'];
$total=array_sum($counts);$favourites=0;foreach($items as $i)if(!empty($i['Favourite']))$favourites++;
$page_title='Wardrobe'; $wardrobe_modern=true; include 'header.php';
function wardrobe_card(array $item): void { $id=(int)$item['WardrobeItemID']; $pref=$item['CatalogueImagePreference']??'processed'; ?>
<article class="wardrobe-card"><a class="wardrobe-card-image" href="wardrobe_item.php?id=<?=$id?>"><img loading="lazy" src="<?=wardrobe_h(wardrobe_image_url($id,$pref,'front'))?>" data-fallback="<?=wardrobe_h(implode(',',array_slice(wardrobe_image_fallback_chain($pref,'front'),1)))?>" onerror="var a=this.dataset.fallback.split(',');if(a.length&&a[0]){this.src='wardrobe_image.php?id=<?=$id?>&view='+a.shift();this.dataset.fallback=a.join(',');}else{this.onerror=null;}" alt="<?=wardrobe_h(trim(($item['Brand']??'').' '.($item['Name']??'')))?>"></a><?php if(!empty($item['Favourite'])):?><span class="wardrobe-favourite" aria-label="Favourite">♥</span><?php endif;?><div class="wardrobe-card-body"><div class="wardrobe-card-brand"><?=wardrobe_h($item['Brand']?:ucwords($item['Category']))?></div><h3 class="wardrobe-card-name"><a class="text-reset text-decoration-none" href="wardrobe_item.php?id=<?=$id?>"><?=wardrobe_h($item['Name'])?></a></h3><div class="wardrobe-card-meta"><?=wardrobe_h($item['PrimaryColour']?:ucwords($item['Category']))?></div></div></article><?php }
?>
<main class="wardrobe-shell">
<section class="wardrobe-hero"><div><div class="wardrobe-eyebrow">Your personal collection</div><h1 class="wardrobe-title">What would you like<br>to wear today?</h1><p class="wardrobe-subtitle">Browse your own wardrobe like a fashion store — newest pieces, favourites and every category in one place.</p></div><div class="wardrobe-actions"><a class="wardrobe-btn wardrobe-btn-light" href="wardrobe_outfits.php">Outfits worn</a><a class="wardrobe-btn wardrobe-btn-light" href="wardrobe_backlog.php">Image backlog</a><a class="wardrobe-btn wardrobe-btn-dark" href="wardrobe_add.php">＋ Add clothing</a></div></section>
<form class="wardrobe-searchbar"><input class="form-control" name="q" value="<?=wardrobe_h($q)?>" placeholder="Search brand, item, colour, material or tag"><select class="form-select" name="category"><option value="">All categories</option><?php foreach(wardrobe_allowed_categories() as $c):?><option value="<?=$c?>" <?=$category===$c?'selected':''?>><?=ucwords($c)?></option><?php endforeach;?></select><button class="btn btn-dark">Search wardrobe</button></form>
<nav class="wardrobe-category-strip" aria-label="Wardrobe categories"><a class="wardrobe-chip <?=$category===''?'active':''?>" href="wardrobe.php">All</a><?php foreach(wardrobe_allowed_categories() as $c):if(empty($counts[$c]))continue;?><a class="wardrobe-chip <?=$category===$c?'active':''?>" href="wardrobe.php?category=<?=urlencode($c)?>"><?=ucwords($c)?></a><?php endforeach;?></nav>
<section class="wardrobe-section"><div class="wardrobe-section-head"><div><div class="wardrobe-eyebrow"><?= $q||$category?'Your results':'Latest arrivals'?></div><h2 class="wardrobe-section-title"><?= $deleted?'Recently deleted':($category?ucwords($category):($q?'Search results':'Newest in your wardrobe'))?></h2></div><?php if($q||$category||$deleted):?><a class="wardrobe-section-link" href="wardrobe.php">Clear filters</a><?php else:?><a class="wardrobe-section-link" href="wardrobe.php?deleted=1">View bin</a><?php endif;?></div>
<?php if(!$items):?><div class="wardrobe-empty"><h2>No clothing found</h2><p class="text-muted">Try another search or add something new to your wardrobe.</p><a class="wardrobe-btn wardrobe-btn-dark" href="wardrobe_add.php">Add clothing</a></div><?php else:?><div class="wardrobe-grid"><?php foreach($items as $item)wardrobe_card($item);?></div><?php endif;?></section>
</main><?php include 'footer.php';?>
